### ISSUE TITLE
Wrongly reported critical security issue "Zeroconf networking should be disabled." on Centos

### ISSUE THREAD

**Issue by schweikert** [Microsoft/OMS-Agent-for-Linux#843]
omsagent/omsbaseline is reporting a critical security issue on CentOS 7.4 machines: "Zeroconf networking should be disabled":

    NAME | Zeroconf networking should be disabled.
    CCEID | CCE-14054-1
    RULE SEVERITY | Critical
    FULL DESCRIPTION | Zeroconf networking should be disabled. (disabled)
    POTENTIAL IMPACT | An attacker could use abuse this to gain information on network systems, or spoof DNS requests due to flaws in its trust model
    ACTUAL VALUE | open /etc/network/interfaces: no such file or directory

As can be seen in "ACTUAL VALUE" , the check that is done doesn't work on CentOS/RHEL machines, because it assumes that the network configuration is done Debian/Ubuntu-style with /etc/network/interfaces. On CentOS I think that you should only check that the avahi-dnsconfd service is disabled (plus avahi-daemon, but that is checked already).

**Comment by lonevvolf** [comment]
Seconded - I am actually surprised that the check fails.  As far as I can see, it is trying to confirm that there are no lines matching "ipv4ll" in the (missing) file /etc/network/interfaces.  Shouldn't a missing file also pass the CheckNoMatchingLines test?

**Comment by srice01** [comment]
If it helps, we are seeing this problem as well so it would be good if this issue was addressed as currently we are seeing "false positives" for this issue on all of our Azure VMs in Security Center.

**Comment by pmdci** [comment]
Same here. CentOS 7.6 having the same issue and the file /etc/network/interfaces doesn't exist. So...

**Comment by bbaassssiiee** [comment]
It is even more complicated! `/etc/systconfig/network` is changed by **cloud-init**.
I ran my ansible playbook to disable zeroconf networking as per [https://access.redhat.com/solutions/8627](https://access.redhat.com/solutions/8627)

```yaml
- name: check presence of sysconfig network file
  stat:
    path: /etc/sysconfig/network
  register: sysconfig

- name: disable zeroconf networking
  when: sysconfig.stat.exists
  lineinfile:
    dest: /etc/sysconfig/network
    regexp: '^NOZEROCONF'
    line: 'NOZEROCONF=yes'
    state: present
```

## But I found this file changed by an MS agent after a while:
```
cat /etc/sysconfig/network
# Created by cloud-init on instance boot automatically, do not edit.
#
NETWORKING=yes
```
